### ISSUE TITLE
Stylesheet error related to .table-striped 

### ISSUE THREAD

**Issue by bottomlesspit** [sii/siptrackweb#31]
.table-striped>tbody>tr:nth-of-type(odd) {
    background-color: #f9f9f9;
}

This above part is added to the odd rows and breaks the stylesheet causing white rows instead of the expected color red.

Error seen here:

![image](https://user-images.githubusercontent.com/27802870/42020048-121028b2-7ab7-11e8-9237-3e76980cb02c.png)

Similar issue discussed here:

https://github.com/swiss/styleguide/issues/358

**Comment by stemid** [comment]
This was caused by use of an old class to mark a table row as disabled. I've updated all the new bootstrap styled tables to use .text-danger and .danger classes instead.

There still remain old tables that don't use the bootstrap styling but this is no high priority so I'm leaving them for some future commit.
